### ISSUE TITLE
Instructions missing in step 11 of full_riscv.tlv ?

### ISSUE THREAD

**Issue by pcotret** [stevehoover/LF-Building-a-RISC-V-CPU-Core#3]
Figure found in the edX course:
![isa](https://courses.edx.org/assets/courseware/v1/a90c7a9e803e20a16ad61b6d1e0fd58c/asset-v1:LinuxFoundationX+LFD111x+1T2021+type@asset+block/Instruction_decode_table.png)

In [full_riscv.tlv, step 11](https://github.com/stevehoover/LF-Building-a-RISC-V-CPU-Core/blob/main/full_riscv.tlv#L143), it seems that instructions in the right column aren't decoded.

Is it intentional?

**Comment by stevehoover** [comment]
Thanks for pointing this out. I think this must be a left-over file. I deleted it. The solutions shouldn't be easily accessible. The reference solutions should only be visible via the readme link with code hidden. Hope you enjoyed the course!
