### ISSUE TITLE
Uncommenting m4+rf macro cause loosing all signals in Waveform

### ISSUE THREAD

**Issue by DavidTurny** [stevehoover/LF-Building-a-RISC-V-CPU-Core#4]
Hi,

If I uncomment the m4+rf macro in the [starting point code](https://makerchip.com/sandbox?code_url=https:%2F%2Fraw.githubusercontent.com%2Fstevehoover%2FLF-Building-a-RISC-V-CPU-Core%2Fmaster%2Frisc-v_shell.tlv) and compile the project then no signal will be visible in Waveform anymore with the exception of clk and rst (so I lost every signal that I had before).
The TLV version line is this: 
\m4_TLV_version 1d: tl-x.org

**Details**

If I have this simple PC logic code:

![kép](https://user-images.githubusercontent.com/114754950/232323855-624fda49-25fb-4c22-9849-a125feffcd8f.png)

then I see this Waveform after compilatioin:

![kép](https://user-images.githubusercontent.com/114754950/232323898-f1045b9b-3e4e-4eec-9095-fedcea2d5e5f.png)

When I uncomment the m4+rf macro line like this:

![kép](https://user-images.githubusercontent.com/114754950/232323953-a60b8bfb-abd2-448a-87a1-8649e0c3dac1.png)

then after compilation I get this Waveform:

![kép](https://user-images.githubusercontent.com/114754950/232323982-d1c02347-e0e7-43f0-8209-a17f7afff6ae.png)

Br,
David

**Comment by stevehoover** [comment]
Click on the "+" before "TLV".

**Comment by DavidTurny** [comment]
:D Thank you.
